version: '3'
services:
  nginx:
    build: nginx
    ports:
      - "8082:80"
    volumes:
      - ./application:/var/www/html
    networks:
      - snasa2
  php:
    build: php
    volumes:
      - ./application:/var/www/html
    networks:
      - snasa2
networks:
  snasa2:
    driver: "bridge"